#include "Global.h"
sf::RenderWindow* WINDOW;
sf::Clock* CLOCK;
sf::Texture* TEXTURE_GALAXY;
sf::Texture* TEXTURE_BUTTON;
sf::Texture* TEXTURE_UFO;
sf::Texture* TEXTURE_BULLET;
sf::Texture* TEXTURE_EXPLOSION;
sf::Font FONT;